### ISSUE TITLE
Nós, como EPS, gostaríamos de fazer o RoadMap para cada papel.

### ISSUE THREAD

**Issue by guibaldissera** [fga-gpp-mds/2018.1_Nexte#173]
## Descrição

Essa issue tem como objetivo adicionar RoadMap para os papéis de DevOps, Arquiteto, Scrum Master e PO.

## Critérios de Aceitação

- [x] RoadMap para DevOps;
- [x] RoadMap para Arquiteto;
- [x] RoadMap para Scrum Master;
- [x] RoadMap para PO.
